const configs = new Map();
const TTL_MS = 30 * 60 * 1000;
const MODES = new Set(['disabled', 'hardcoded', 'generated', 'portal']);

function cleanUserId(userId) {
  return typeof userId === 'string' && userId.trim() ? userId.trim() : 'anonymous';
}

function prune() {
  const now = Date.now();
  for (const [userId, config] of configs) {
    if (config.expiresAt <= now) configs.delete(userId);
  }
}

export function setWifiConfig(userId, input = {}) {
  prune();
  const mode = MODES.has(input.mode) ? input.mode : 'disabled';
  const ssid = typeof input.ssid === 'string' ? input.ssid.slice(0, 128) : '';
  const password = typeof input.password === 'string' ? input.password.slice(0, 128) : '';
  if ((mode === 'generated' || mode === 'hardcoded') && (!ssid || !password)) {
    throw Object.assign(new Error('SSID and password are required for this WiFi mode'), { status: 400 });
  }
  const config = { mode, ssid, password, expiresAt: Date.now() + TTL_MS };
  configs.set(cleanUserId(userId), config);
  return config;
}

export function getWifiConfig(userId) {
  prune();
  const config = configs.get(cleanUserId(userId));
  return config && config.expiresAt > Date.now() ? config : { mode: 'disabled', ssid: '', password: '' };
}

export function publicWifiConfig(config) {
  return {
    mode: config.mode,
    ssid: config.ssid,
    hasPassword: Boolean(config.password),
    expiresAt: config.expiresAt ?? null,
  };
}

export function clearWifiConfig(userId) {
  configs.delete(cleanUserId(userId));
}

export function wifiConfigHeader(config) {
  if (!config || config.mode === 'disabled') return '';
  const quote = (value) => JSON.stringify(value ?? '');
  const mode = config.mode === 'portal' ? 'PORTAL' : config.mode.toUpperCase();
  return [
    '#pragma once',
    '// Generated by the Chip dashboard for this build. Do not commit this file.',
    `#define CHIP_WIFI_MODE_${mode}`,
    `#define CHIP_WIFI_SSID ${quote(config.ssid)}`,
    `#define CHIP_WIFI_PASS ${quote(config.password)}`,
    `#define CHIP_WIFI_PASSWORD ${quote(config.password)}`,
    '',
  ].join('\n');
}
